### ISSUE TITLE
A symbol in 4.70 CEX needs a fix:

### ISSUE THREAD

**Issue by aldostools** [NzV/PS3Manager_API#2]
This is the correct value:
#define cellFsUtilUmount_symbol                     0x296BD4 // wrong: 0x296B88 // bytes matched: 0x20**  7C8023787CA62B787C641B787C05037838E00000E93E80B0EBC1FFF0E8690000

It should not affect the compatibility, but it's better to have the correct symbols ;)

**Comment by NzV** [comment]
Thank you for report it.
